# VECTORS AND MATRICES

# Vectors in ML

importing Packages

In [115]:
import numpy as np
#defining a vector
v=np.array([1,-1,2])
w=np.array([2, 5, 2])


In [116]:
#addition
print(v+w)
#subtraction
print(v-w)
#scalar multiplication
print(3*v)
#finding length/magnitude of the vector/ norm is for finding out the length
print(np.linalg.norm(v))

#dot product
s=np.dot(v, w)
print(s)


[3 4 4]
[-1 -6  0]
[ 3 -3  6]
2.449489742783178
1


## MATRICES

In [117]:
P = np.array([[1,7], [2,1], [3,2]])
print(P)

[[1 7]
 [2 1]
 [3 2]]


In [118]:
Q = np.array([[1,1],[1,-1], [1,0]])
c1= np.add(P, Q)
c1

array([[2, 8],
       [3, 0],
       [4, 2]])

In [119]:
# subtraction
c2 = np.subtract(P, Q)
c2

array([[0, 6],
       [1, 2],
       [2, 2]])

In [120]:
#Multiplication
R = np.array([[1,3,1],[1,0,1]])
print(R)
c3 = np.dot(P, R)
print(c3)

[[1 3 1]
 [1 0 1]]
[[8 3 8]
 [3 6 3]
 [5 9 5]]


In [121]:
#Determinant of matrices
det = np.linalg.det(c3)
print(det)
#determinant is zero
# s2= np.linalg.inv(c3)
# print(s2) # causes a error because it a singular matrix i.e determinant is zero

0.0


In [122]:
M = np.array([[1,-1], [2,3]])
print(np.linalg.inv(M))

[[ 0.6  0.2]
 [-0.4  0.2]]
